openapi: 3.0.0
info:
  title: MTAA zadanie 2 
  description: Definícia API pre zadanie 2
  version: 0.1.0
tags:
- name: "Zadanie 2"
paths:
  /offers:
    get:
      tags:
        - "Zadanie 2"
      summary: Vráti informácie o ponukách nehnuteľností.
      description: Pre získanie tejto informácie sa použije príkaz `SELECT * FROM posts INNER JOIN users ON posts.users_id = users.id`
      responses:
        '200':
          description: Očakávaná odpoveď vo formáte [JSON](https://www.json.org/json-en.html)
          content:
            application/json:
              schema: 
                type: object    
                properties:  
                  id:
                    type: number   
                  like_status: 
                    type: integer

                  added_date:
                    type: string  
                  title: 
                    type: string
                  text:
                    type: string 
                  users_id: 
                    type: number
                  property_id:
                    type: number  
                  name:
                    type: string
                  surname:
                    type: string
                  email: 
                    type: string
                  telephone: 
                    type: string
                  profile_picture_ref:
                    type: number
                  image_link:
                    type: string

                example: 
                  id: 1
                  like_status: 25
                  added_date: "2022-01-31T23:00:00.000Z"
                  title: "Priestranný byt na predaj"
                  text: "Tento byt sa nachádza v pokojnej časti mesta."
                  users_id: 1
                  property_id: 1
                  name: "Jozef"
                  surname: "Mikloš"
                  email: "jozo.miklos@gmail.com"
                  telephone: "0954555666"
                  profile_picture_ref: null
                  image_link: "link_ku_obrazku"
  /myOffers:
      put:
        tags:
          - "Zadanie 2"
        summary: Vráti informácie o ponuke nehnuteľností daného používateľa.
        description: Pre získanie tejto informácie sa použije príkaz `SELECT * FROM property INNER JOIN location ON property.location_id = location.id INNER JOIN posts ON posts.property_id = property.id WHERE posts.users_id = ?`
        requestBody:
          content: 
            application/json:
              schema:      
                type: object
                properties:          
                  user_id:
                    type: number
                example: 
                  user_id: 1
        responses:
          '200':
            description: Očakávaná odpoveď vo formáte [JSON](https://www.json.org/json-en.html)
            content:
              application/json:
                schema: 
                  type: object    
                  properties:          
                    id: 
                      type: number
                    type: 
                      type: string
                    size: 
                      type: number
                    price:
                      type: string
                    description: 
                      type: string
                    rooms:
                      type: number
                    image_link:
                      type: string
                    location_id:
                      type: number
                    users_id:
                      type: number
                    state: 
                      type: string
                    city: 
                      type: string
                    street: 
                      type: string
                    postal_code: 
                      type: string
                    like_status: 
                      type: number
                    added_date: 
                      type: number
                    title: 
                      type: string
                    text: 
                      type: string
                    property_id: 
                      type: number    
                  example: 
                    id: 2
                    type: "dom"
                    size: 125
                    price: "200000"
                    description: "Nehnuteľnosť je v zachovalom stave"
                    rooms: "4"
                    image_link: "toto je link k obrázku"
                    location_id: 2
                    users_id: 2
                    state: "Slovensko"
                    city: "Ružomberok"
                    street: "Gorkého 54"
                    postal_code: "07106"
                    like_status: 4
                    added_date: "2021-04-13T22:00:00.000Z"
                    title: "Dom na predaj"
                    text: "Dom sa nachádza v pokojnej časti mesta"
                    property_id: 2  
          
  /register:
    post:
      tags:
        - "Zadanie 2"
      summary: umožní pridanie používateľa do databázy.
      description: Pre získanie tejto informácie sa použije príkaz `INSERT INTO users (name, surname, email, telephone, profile_picture_ref) VALUES (?,?,?,?,?)`
      requestBody:
        content: 
          application/json:
            schema:      
              type: object
              properties:          
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                telephone:
                  type: string
                profile_picture_ref:
                  type: string
              example: 
                name: 'Jozko'
                surname: 'Mrkvicka'
                email: 'jozko.mrkva@stuba.sk'
                telephone: '0940111111'
                profile_picture_ref: 'UnknownImage.jpg'
      responses:
        '200':
          description: User was created.
        '400':
          description: Registration wasn't successfull.
          
  /login:
    put:
      tags:
        - "Zadanie 2"
      summary: umožní prihlásenie používateľa do aplikácie.
      description: Pre získanie tejto informácie sa použije príkaz `SELECT * FROM users WHERE email = ? AND name = ?`
      
      requestBody:
        content: 
          application/json:
            schema:      
              type: object
              properties:          
                name:
                  type: string
                email:
                  type: string
              example: 
                name: 'Jozko'
                email: 'jozko.mrkva@stuba.sk'
      responses:
        
        '400':
          description: Invalid name or email
        '200':
          description: Očakávaná odpoveď vo formáte [JSON](https://www.json.org/json-en.html)
          content:
            application/json:
              schema:      
                type: object
                properties:     
                  id:
                    type: number     
                  name:
                    type: string
                  surname:
                    type: string
                  email:
                    type: string
                  telephone:
                    type: string
                example:
                  id: 4
                  name: 'Jozko'
                  surname: 'Mrkvicka'
                  email: 'jozko.mrkva@stuba.sk'
                  telephone: '0940111111'
                  profille_picture_ref: 'UnknownProfile.jpg'
  /change:
    put:
      tags:
        - "Zadanie 2"
      summary: umožní zmenenie informácií o nehnuteľnosti používateľa.
      description: Pre získanie tejto informácie sa použije príkaz `UPDATE property SET type = ?, size = ?, price = ?, description = ?, rooms = ?, image_link = ? WHERE id = ${property_id} AND users_id = ${user_id}`
      
      
      requestBody:
        content:
            application/json:
              schema:      
                type: object
                properties:     
                    property_id: 
                      type: number
                    user_id: 
                      type: number
                    type: 
                      type: string
                    size: 
                      type: number
                    price: 
                      type: string
                    description: 
                      type: string
                    rooms: 
                      type: number
                    image_link: 
                      type: string
                example:
                    property_id: 1
                    user_id: 1
                    type: "dom"
                    size: 200
                    price: "200000"
                    description: "zmenenie"
                    rooms: 4
                    image_link: "linka"
      responses:
        '200':
          description: Change was successfull.
        '400':
          description: Oops something went wrong.
  /comments:
    put:
      tags:
        - "Zadanie 2"
      summary: umožní zmenenie informácií o nehnuteľnosti používateľa.
      description: Pre získanie tejto informácie sa použije príkaz `SELECT * FROM comments WHERE comments.posts_id = ?`
      requestBody:
        content:
            application/json:
              schema:      
                type: object
                properties:     
                    post_id: 
                      type: number
                example:
                    post_id: 1
                    
      responses:
        '200':
          description: comments are shown.
          content:
              application/json:
                schema: 
                  type: object   
                  properties:          
                    added_date:
                      type: string
                    comment: 
                      type: string
                    like_status:
                      type: number
                    posts_id:
                      type: number
                    users_id:
                      type: number
                  example: 
                    added_date: '2022-03-22'
                    comment: 'naozaj pekne'
                    like_status: 56
                    posts_id: 1
                    user_id: 1 
        '400':
          description: Oops something went wrong.           
  /domy:
      get:
        tags:
          - "Zadanie 2"
        summary: Vráti dostupnú ponuku domov.
        description: Pre získanie tejto informácie sa použije príkaz `SELECT * FROM property WHERE type = 'dom' `
        responses:
          '200':
            description: Očakávaná odpoveď vo formáte [JSON](https://www.json.org/json-en.html)
            content:
              application/json:
                schema: 
                  type: object           
                  properties:          
                    name:
                      type: string
                    surname:
                      type: string
                    like_status: 
                      type: integer
                    added_date:
                      type: string
                    title: 
                      type: string
                    image_link:
                      type: string
                    type:
                      type: string
                  example: 
                    name: 'Jozko'
                    surname: 'Mrkvicka'
                    like_status: 56
                    added_date: '2022-03-22'
                    title: '2-dom byt na predaj v kľudnej časti mesta'
                    type: 'dom'
  
  /byty:
      get:
        tags:
          - "Zadanie 2"
        summary: Vráti dostupnú ponuku bytov.
        description: Pre získanie tejto informácie sa použije príkaz `SELECT * FROM posts WHERE type = 'byt' `
        responses:
          '200':
            description: Očakávaná odpoveď vo formáte [JSON](https://www.json.org/json-en.html)
            content:
              application/json:
                schema: 
                  type: object   
                  properties:          
                    name:
                      type: string
                    surname:
                      type: string
                    like_status: 
                      type: integer
                    added_date:
                      type: string
                    title: 
                      type: string
                    image_link:
                      type: string
                    type:
                      type: string
                  example: 
                    name: 'Jozko'
                    surname: 'Mrkvicka'
                    like_status: 56
                    added_date: '2022-03-22'
                    title: '2-izbový byt na prenájom v kľudnej časti mesta'
                    type: 'byt' 
  /zmaz:
    delete:
      tags:
        - "Zadanie 2"
      summary: Zmaže zadaný inzerát.
      description: Pre zmazanie daného inzerátu sa použije príkaz `DELETE location, property, posts 
            FROM posts INNER JOIN property ON posts.property_id = property.id 
            INNER JOIN location ON location.id = property.location_id 
            WHERE property.id = ? AND posts.users_id = ? `
      responses:
          '200':
            description: Property was deleted.
          '400':
            description: Invalid ID of the property.
  